# Site settings
title: OpenSpending Community
short_title: OpenSpending Community
description: OpenSpending is a free, open and global platform to search, visualise and analyse fiscal data in the public sphere.
baseurl: ""
issues_url: https://github.com/openspending/next/issues
url: "http://community.openspending.org/" # the base hostname & protocol for your site
github_username: openspending
github_repo: community.openspending.org
paypal: admin@okfn.org
contact: https://discuss.okfn.org/c/openspending
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

devs:
  -
      name: Sam Smith
      github: mintcanary
  -
      name: Dan Fowler
      github: danfowler
  -
      name: Paul Walsh
      github: pwalsh

contributors:
  -
      name: Rufus Pollock
      link: http://rufuspollock.org/

supporters:
  -
    name: Global Initiative for Fiscal Transparency
    footer_logo: gift-footer.png

googleanalytics: UA-8271754-63

markdown: kramdown

markdown_ext: "markdown,mkdown,mdown,mkdn,mkd,md"

permalink: pretty

related_projects:
  -
      name: OpenGovernmentData.org
      link: http://opengovernmentdata.org/
  -
      name: The DataHub
      link: http://datahub.io/
  -
      name: DataCatalogs.org
      link: http://datacatalogs.org/
  -
      name: OpenSpending.org
      link: http://openspending.org/
  -
      name: SchoolOfData.org
      link: http://schoolofdata.org/
  -
      name: OpenDefinition.org
      link: http://opendefinition.org/
  -
      name: Introducing Open Data
      link: http://okfn.org/opendata/

collections:
  eu_datasets:
    output: true
    permalink: /resources/eu/datasets/:path/
  eu_funds:
    output: true
    permalink: /resources/eu/funds/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      edit: true
  -
    scope:
      path: "help"
    values:
      layout: "deprecated"
      section: "help"
  -
    scope:
      path: "blog"
    values:
      layout: "post"
      section: "blog"
  -
    scope:
      path: ""
      type: eu_datasets
    values:
      layout: eu_dataset
  -
    scope:
      path: ""
      type: eu_funds
    values:
      layout: eu_fund
